source 'https://rubygems.org'

gem 'jekyll'
gem 'jekyll-feed'
gem 'jekyll-sitemap'
gem 'jekyll-seo-tag'
gem 'jekyll-paginate'
gem 'jekyll-redirect-from'
gem 'jekyll-archives'
gem 'dotenv', '~> 3.1', '>= 3.1.7'
gem 'wdm'
